src/interfaces/keycloak-config.ts

Valid for Keycloak 2.5.x (credentials): https://github.com/keycloak/keycloak-js-bower/blob/2.5.4/dist/keycloak.js#L596
and for the latest Keycloak: https://github.com/keycloak/keycloak-js-bower/blob/master/dist/keycloak.js#L534

added: support for client secret.

---

package.json
yarn.lock

karma-typescript is not part of package.json, so running `yarn test` fails:
> 01 02 2018 22:47:19.333:ERROR [preprocess]: Can not load "karma-typescript", it is not registered!
Perhaps you are missing some plugin?

fix(build): include karma-typescript

---

.travis.yml
README.md

I've added a travis config file which builds the app.
Note: it doesn't run any tests yet.
I've also added a badge to the readme to show the travis status

chore(build): add travis

---

docs/project/proposals/request-for-change/impersonate-api.md

adding documentation for proposal.

docs: addition of proposal: impersonate api

---

README.md
projects/keycloak-angular/src/lib/core/interceptors/keycloak-bearer.interceptor.ts
projects/keycloak-angular/src/lib/core/interfaces/keycloak-options.ts
projects/keycloak-angular/src/lib/core/services/keycloak.service.ts

```
[x] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
Issue Number: [63](https://github.com/mauriciovigolo/keycloak-angular/issues/63)
Same as before, Only the property name has changed.
```
[ ] Yes
[x] No
```

switch back the bearer interceptor to be enabled by default

---

README.md

```
[ ] Bugfix
[ ] Feature
[*] Documentation content changes
```
Documentation contains the promise-constructor/deferred anti-pattern as described here: https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern
I see no reason to wrap the promise during this example. The only difference between the proposed code, and the existing code is, that the old one returns an `Promise<boolean>` and the new one returns a `Promise<void>`, which makes no …

Improve promise usage in README

---

README.md

```
[ ] Bugfix
[ ] Feature
[*] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[*] No
```

More friendly code

---

README.md

```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
[ ] Yes
[X] No
```

add note about misleading No 'Access-Control-Allow-Origin'

---

README.md

```
[ ] Bugfix
[ ] Feature
```
The link to the contributing document returns a 404 Not Found error.
The link to the contributing document returns the correct page.
```
[ ] Yes
[x] No
```

docs(README): Fix contributing URL

---

examples/webapp/keycloak-heroes-bootstrap/package.json
examples/webapp/keycloak-heroes/package.json
package.json
projects/keycloak-angular/package.json

```
[ ] Bugfix
[x] Feature
```
Issue Number: #250 
```
[ ] Yes
[x] No
```

feat: add support for Keycloak 10

---

README.md

Add hint when doBootstrap haven't called
https://github.com/angular/angular/issues/35205
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

(docs) add bootstrap hint

---

projects/keycloak-angular/src/lib/core/services/keycloak.service.spec.ts
projects/keycloak-angular/src/lib/core/services/keycloak.service.ts

Do not force user to log in when calling getToken()

---

example/scripts/.gitattributes

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
When cloning the project on Windows the shell scripts in `/example/scripts/` had Windows (CRLF) line endings and did not work in the Docker container.
Issue Number: #333 
When cloning on Windows, the scripts have Unix line endings (LF).
```
[ ] Yes
[x] No
```

style: add .gitattributes for shell scripts

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Update readme: add callback events paragraph

---

README.md
projects/keycloak-angular/package.json

More info https://github.com/angular/angular/issues/44745#issuecomment-1015578019

Update supported Angular versions

---

projects/keycloak-angular/src/lib/core/services/keycloak-auth-guard.ts
projects/keycloak-angular/src/lib/core/services/keycloak.service.spec.ts

~~* [ ] Tests for the changes have been added (for bug fixes / features)~~
~~* [ ] Docs have been added / updated (for bug fixes / features)~~
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```
In the Guard a promise is being build using an async function which itself resolves in a promise. 
Using a single async method and therefore a single promise in the guard.
The async-modifier in the service spec was unnecessary as the function itself is returning a promise without awaiting anything. …

refactor: promise handling

---

projects/keycloak-angular/src/lib/core/core.module.spec.ts
projects/keycloak-angular/src/lib/core/core.module.ts
projects/keycloak-angular/src/lib/core/interceptors/keycloak-bearer.interceptor.spec.ts
projects/keycloak-angular/src/lib/core/interceptors/keycloak-bearer.interceptor.ts
projects/keycloak-angular/src/lib/core/interfaces/keycloak-event.ts
projects/keycloak-angular/src/lib/core/interfaces/keycloak-options.ts
projects/keycloak-angular/src/lib/core/services/keycloak-auth-guard.ts
projects/keycloak-angular/src/lib/core/services/keycloak.service.spec.ts
projects/keycloak-angular/src/lib/core/services/keycloak.service.ts
projects/keycloak-angular/src/lib/keycloak-angular.module.ts
projects/keycloak-angular/src/public_api.ts
projects/keycloak-angular/src/test.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

Fix license link

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

README.md: fix badges/switch to shields.io for all

---

README.md
example/package-lock.json
example/package.json
example/src/app/app.module.ts
example/tsconfig.json
package-lock.json
package.json
projects/keycloak-angular/package.json
projects/keycloak-angular/src/lib/core/services/keycloak.service.ts

```
[ ] Bugfix
[x] Feature
```
Issue Number: #385
```
[ ] Yes
[X] No
```

feature: update to Keycloak 17 (#397)

---

projects/keycloak-angular/src/lib/core/services/keycloak.service.ts

```
[x] Bugfix
[ ] Feature
```
Issue Number: 407
Not have error due the missing parameter in the updateToken.
```
[ ] Yes
[x] No
```

bugfix: fix updateToken parameter error #407

---

projects/keycloak-angular/src/lib/core/interceptors/keycloak-bearer.interceptor.ts
projects/keycloak-angular/src/lib/core/services/keycloak.service.ts

- Related to issue #409
```
[x] Bugfix
[ ] Feature
```
Issue Number: 409
```
[ ] Yes
[ x] No
```

fix: updateToken when an exception happens

---

README.md
package-lock.json
package.json
projects/keycloak-angular/package.json

Add support for Keycloak JS version 19

---

README.md
package-lock.json
package.json
projects/keycloak-angular/package.json

```
[ ] Bugfix
[ ] Feature
[X] Other... Please describe: bump keycloak
```
```
[ ] Yes
[X] No
```

chore: add support for Keycloak JS version 20

---

projects/example/src/app/app.component.ts

It seems it was removed inadvertently in #452.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

Example: add missing `ngOnit`

---

.github/dependabot.yml

```
[ ] Bugfix
[ ] Feature
[X] CI related changes
[] Other... Please describe:
```
Monthly GitHub Actions updates with Dependabot.
```
[ ] Yes
[X] No
```

Add dependabot config for GitHub Actions updates

---

README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

README.md: fix badges

---

README.md

```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
[ ] Yes
[X] No
```

docs: fix paths array variable name

---

README.md

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```

README.md: fix lint and tweak snippets

---

README.md
package-lock.json
package.json
projects/keycloak-angular/package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feature: support keycloak-js v21.1.0-1

---

README.md
package-lock.json
package.json
projects/example/docker-compose.yml
projects/keycloak-angular/package.json

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

Support keycloak-js v22.0.0 (#504)

---

README.md
package-lock.json
package.json
projects/example/docker-compose.yml
projects/keycloak-angular/package.json

Support keycloak-js v22.0.0 (#504) (#505)

---

projects/keycloak-angular/src/lib/core/interfaces/keycloak-options.ts

```
[ ] Bugfix
[ ] Feature
[X] Refactoring (no functional changes, no api changes)
```
```
[ ] Yes
[X] No
```

keycloak-options.ts: fix typo

---

README.md
package-lock.json
package.json
projects/example/docker-compose.yml
projects/keycloak-angular/package.json
projects/keycloak-angular/src/lib/core/services/keycloak.service.ts

* [] Docs have been added / updated (for bug fixes / features)
```
[ ] Bugfix
[x] Feature
```
Issue Number: #545
```
[ ] Yes
[x] No
```

feat: keycloak-js@24 update

---

README.md
package-lock.json
package.json
projects/example/docker-compose.yml
projects/keycloak-angular/package.json
projects/keycloak-angular/tsconfig.lib.json
tsconfig.json

```
[ ] Bugfix
[x] Feature
```
Fixes #583 
```
[x] Yes
[ ] No
```
[Support for UMD distribution was removed from keycloak-js](https://github.com/keycloak/keycloak/blob/98a6ddead0d7121470f5d17be635e1f4dbf3058e/docs/documentation/upgrading/topics/changes/changes-26_0_0.adoc#support-for-the-umd-distribution-has-been-removed), which makes it necessary to update the `moduleResolution` to e.g. `bundler`

feat: Add support for keycloak-js@26

---

README.md
package-lock.json
package.json
projects/example/docker-compose.yml
projects/keycloak-angular/package.json
projects/keycloak-angular/tsconfig.lib.json
tsconfig.json

Signed-off-by: tomaThomas <tomathomas@mailbox.org>
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

feat: Add support for keycloak-js@26 (#585)

---

projects/keycloak-angular/src/lib/features/keycloak.feature.ts
projects/keycloak-angular/src/lib/services/auto-refresh-token.service.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

bugfix: fix typos in auto-refresh-token.service.ts & keycloak.feature.ts

---

docs/migration-guides/v19.md

```
[ ] Bugfix
[ ] Feature
```
Hello @mauriciovigolo,
thank you for providing this great library to the community.
I've fixed two typos in migration guide, so please take a look.

Fix typos in v19 migration guide
